# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

switch:
  - platform: rpi_gpio
    switches:
      - { port: 17, name: "Čekić muško", invert_logic: true }
      - { port: 27, name: "Čekić žensko", invert_logic: true }
      - { port: 22, name: "Zvono muško", invert_logic: true }
      - { port: 23, name: "Zvono žensko", invert_logic: true }
      - { port: 5,  name: "Kazaljke pozitivna", invert_logic: true }
      - { port: 6,  name: "Kazaljke negativna", invert_logic: true }
      - { port: 13, name: "Razglas", invert_logic: true }
      - { port: 19, name: "Zvučnici prebacivanje 1", invert_logic: true }
      - { port: 26, name: "Zvučnici prebacivanje 2", invert_logic: true }
      - { port: 20, name: "LED klima grije" }
      - { port: 21, name: "LED klima hladi" }
      - { port: 16, name: "LED crveni – greška" }
      - { port: 12, name: "LED zeleni – ispravno" }

binary_sensor:
  - platform: rpi_gpio
    sensors:
      - { port: 4,  name: "Prekidač 1", bouncetime: 50, pull_mode: "UP" }
      - { port: 18, name: "Prekidač 2", bouncetime: 50, pull_mode: "UP" }
      - { port: 25, name: "Prekidač 3", bouncetime: 50, pull_mode: "UP" }

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

logger:
  default: warning
  logs:
    homeassistant.core: info
    homeassistant.components.system_log.external: info
    greeclimate.network: error

recorder:
  purge_keep_days: 7
  auto_purge: true
  commit_interval: 30
  exclude:
    domains:
      - updater
      - weather
      - update
      - zone
      - person
      - conversation
    entities:
      - sensor.time
      - sensor.date
